spring:
  application:
    name: api-usuarios

server:
  port: 8082

datasource:
  host: jdbc:mysql://localhost:3307/bd_usuarios?useSSL=false&serverTimezone=America/Sao_Paulo
  user: coti
  pass: coti